SET search_path TO WixDaWish;

INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Accordion', 'D://components/Accordion.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Alerts','D://components/Alerts.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Badge','D://components/Badge.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Breadcrumb','D://components/Breadcrumb.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Buttons','D://components/Buttons.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Button group','D://components/Button_group.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Card','D://components/Card.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Carousel','D://components/Carousel.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Close button','D://components/Close_button.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Collapse','D://components/Collapse.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Dropdowns','D://components/Dropdowns.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','List group','D://components/List_group.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Disabled','Modal','D://components/Modal.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Maintenance','Navs','D://components/Navs.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Maintenance','Tabs','D://components/Tabs.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Maintenance','Navbar','D://components/Navbar.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Maintenance','Offcanva','D://components/Offcanvas.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Pagination','D://components/Pagination.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Disabled','Popover','D://components/Popovers.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Progress','D://components/Progress.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Scrollspy','D://components/Scrollspy.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Spinner','D://components/Spinners.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Toast','D://components/Toasts.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Tooltip','D://components/Tooltips.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H1','D://components/H1.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H2','D://components/H2.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H3','D://components/H3.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H4','D://components/H4.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H5','D://components/H5.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','H6','D://components/H6.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','p','D://components/p.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','a','D://components/a.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','ul','D://components/ul.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','li','D://components/li.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Table','D://components/table.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','TR','D://components/tr.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','TH','D://components/th.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','TD','D://components/td.html')
INSERT INTO components (logadded,status,name, html_path) VALUES ( '12-06-2021','Active','Image','D://components/Image.html')