---
application:
  name: "nodejs-postgresql"
  project: "test1"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "quotes"
  version: "11"
routers:
- name: "main-nodejs-postgresql"
  routes:
  - application_name: "nodejs-postgresql"
    paths:
    - "/*"
